language: python
os: linux
python: 3.6
jobs:
  include:
    - name: Run Linter
      install: pip install pycodestyle
      script: bash qa/detect-common-errors.sh && bash qa/detect-dead-code.sh && bash qa/run-linter.sh;
    - name: Run PyDocstyle
      install: pip install pycodestyle
      script: bash qa/check-docstyle.sh

