name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

env:
  REGISTRY:  ghcr.io
  REPOSITORY: fabric8-analytics-server
  DEFAULT_TAG: latest
  FULL_NAME: bayesian-bayesian-api
  TESTS_IMAGE: server-tests
  ORGANIZATION: practice-fabric8-analytics

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
          git checkout FETCH_HEAD
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.CR_PAT }}
          commands: |
            build-image
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.CR_PAT }}
      - name: Build image
        run: bash qa/runtest.sh 
      - name: Tag and Push
        run: |
          docker tag ${{env.TESTS_IMAGE}}:${{env.DEFAULT_TAG}} ${{env.REGISTRY}}/${{env.ORGANIZATION}}/${{env.REPOSITORY}}/${{env.FULL_NAME}}:${{env.DEFAULT_TAG}};
          docker push ${{env.REGISTRY}}/${{env.ORGANIZATION}}/${{env.REPOSITORY}}/${{env.FULL_NAME}}:${{env.DEFAULT_TAG}};
      - name: Make a Pull request comment - Notify Developer
        uses: mshick/add-pr-comment@v1
        with: 
          message: |
           @${{ github.event.issue.pull_request.user.login }} your image is avaliablle in the registry:
           ``` docker pull quay.io/bayesian-bayesian-api:latest ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true 
        
        
